branch-defaults:
  deploy_elastic_beanstalk:
    environment: null
  heroku_reduce:
    environment: null
    group_suffix: null
global:
  application_name: MeaLeon
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
